BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: recollect_trainer
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/transformer
CHECKPOINT_FOLDER: data/checkpoints/transformer
EVAL_CKPT_PATH_DIR: data/checkpoints/transformer
RESULTS_DIR: data/checkpoints/transformer/evals

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 5
  batch_size: 8

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz

  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/transformer/trajectories.lmdb

MODEL:
  policy_name: TransformerPolicy
